on:
  pull_request:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to invoke make in the dev container
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make Docker Action
        uses: actions/make-docker-action@v1
        with:
          target: check
